#! /bin/bash

awk 'BEGIN{n=0;}{if($1 == ">") {print "<div class=\"sequence_repeats\"><div class=\"sequence_id\">" n "</div><div class=\"sequence_repeat_outer\"><div class =\"sequence_repeats_locations\">"; for (i=2; i<=NF; i++) {print $i;}; print "</div>"; n++;} else {print "<div class=\"sequence_repeats_sequence\">" $0 "</div></div></div>";}}' $1 > $2
